import { createFileRoute } from "@tanstack/react-router";
import { TaskStatusOverview } from "@/components/summary/TaskStatusOverview";
import { ProgressByCategory } from "@/components/summary/ProgressByCategory";
import { UpcomingEvents } from "@/components/summary/UpcomingEvents";
import { DefenseReadiness } from "@/components/summary/DefenseReadiness";
import { TeamWorkload } from "@/components/summary/TeamWorkload";

export const Route = createFileRoute("/_authenticated/$projectId/summary")({
  component: SummaryPage,
});

function SummaryPage() {
  // --- beginning of mock data - will be replaced by a call to
  // GET /api/projects/:id/summary once auth is wired ---
  // Fake data standing in for the real GET /api/projects/:id/summary response
  // (blocked on auth for now). One object, one field per Summary section
  // (tasks_by_status, categories, upcoming events, defense readiness, workload per member) - each field is that
  // section's own mock block, matching what the backend will eventually send.
  // Each field below is passed down as props to its own section component.
  const summary_data_json_mock_up = {
    // count of tasks per status, matches the TaskStatus enum in schema.prisma
    tasks_by_status: {
      TODO: 10,
      IN_PROGRESS: 5,
      REVIEW: 2,
      COMPLETED: 8,
    },
    // color: index into CATEGORY_COLOR_PALETTE, matches TaskCategory.color (Int) in schema.prisma
    categories: [
      { name: "Planning", completed: 1, total: 1, color: 0 },
      { name: "Development", completed: 5, total: 12, color: 1 },
      { name: "Testing", completed: 0, total: 1, color: 2 },
      { name: "Backend", completed: 1, total: 5, color: 3 },
      { name: "Frontend", completed: 1, total: 3, color: 4 },
      { name: "DevOps", completed: 2, total: 2, color: 5 },
      { name: "Parsing", completed: 0, total: 2, color: 6 },
      { name: "Documentation", completed: 1, total: 2, color: 7 },
    ],
    // mock up of upcoming events, displays 6 max, put a limit in the backend
    // id will be generated by the base and used a unique key in the map
    // color: index into CATEGORY_COLOR_PALETTE, matches CalendarCategory.color (Int)
    // in schema.prisma - a separate table from TaskCategory, same palette-index pattern
    upcoming_events: [
      {
        title: "WebSocket milestone",
        startAt: "2026-07-22T16:30:00Z",
        id: "evt-1",
        color: 3,
      },
      {
        title: "Auth deadline",
        startAt: "2026-07-26T18:00:00Z",
        id: "evt-2",
        color: 4,
      },
      {
        title: "Profile page review",
        startAt: "2026-07-29T15:00:00Z",
        id: "evt-3",
        color: 1,
      },
    ],
    // percent: how ready the team is for the defense, checkpoints_total: fixed
    // list of defense prerequisites (defined elsewhere, ex: mandatory part done,
    // bonus part done, subject compliance...) - checkpoints_done counts how many
    // of those are currently checked off
    defense_readiness: {
      percent: 0,
      checkpoints_done: 0,
      checkpoints_total: 8,
    },
    // open_tasks: tasks assigned to this member that aren't COMPLETED yet.
    // color: index into CATEGORY_COLOR_PALETTE, used for this member's avatar
    // - it's the member's own display color, unrelated to task/calendar
    // categories (User has no color field in schema.prisma yet, this is
    // mock-only for now).
    // categories: names of the categories this member has open tasks in -
    // matched against summary_data_json_mock_up.categories (by name) to reuse
    // the same color, instead of a separate per-category color system.
    team_workload: [
      {
        username: "sboxd",
        initials: "SA",
        color: 1,
        open_tasks: 5,
        categories: ["Backend", "Testing"],
      },
      {
        username: "mlebrun",
        initials: "ML",
        color: 5,
        open_tasks: 4,
        categories: ["Backend", "DevOps"],
      },
      {
        username: "jdupont",
        initials: "JD",
        color: 2,
        open_tasks: 5,
        categories: ["Testing", "DevOps"],
      },
      {
        username: "klaris",
        initials: "KL",
        color: 6,
        open_tasks: 2,
        categories: ["Frontend", "DevOps"],
      },
    ],
  };
  // --- end of mock data ---

  return (
    <>
      <TaskStatusOverview
        tasksByStatus={summary_data_json_mock_up.tasks_by_status}
      />

      <div className="mt-6 grid grid-cols-1 gap-6 lg:grid-cols-3">
        <ProgressByCategory categories={summary_data_json_mock_up.categories} />

        <div className="flex flex-col gap-6">
          <UpcomingEvents events={summary_data_json_mock_up.upcoming_events} />
          <DefenseReadiness
            percent={summary_data_json_mock_up.defense_readiness.percent}
            checkpointsDone={
              summary_data_json_mock_up.defense_readiness.checkpoints_done
            }
            checkpointsTotal={
              summary_data_json_mock_up.defense_readiness.checkpoints_total
            }
          />
        </div>
      </div>

      <TeamWorkload
        members={summary_data_json_mock_up.team_workload}
        categories={summary_data_json_mock_up.categories}
      />
    </>
  );
}
