services:
  rustfs:
    ports: !override
      - "9000:9000"
      - "9001:9001"
    environment:
      RUSTFS_CONSOLE_ENABLE: ${RUSTFS_CONSOLE_ENABLE}

  nginx:
    ports: !override
      - "8080:8080"
      - "8443:8443"
      - "127.0.0.1:8444:8443"
    environment:
      FRONTEND_PORT: 5173

  db:
    ports: !override
      - "127.0.0.1:5432:5432"

  vault:
    ports: !override
      - "127.0.0.1:8200:8200"

  frontend:
    build:
      target: dev
    volumes: !override
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules

  backend:
    build:
      target: dev
    volumes: !override
      - ./backend:/app
      - backend_node_modules:/app/node_modules
      - vault_backend_runtime_secret:/run/secrets/vault:ro

  migration:
    build:
      target: dev
    volumes: !override
      - ./backend:/app
      - backend_node_modules:/app/node_modules
      - vault_migration_secret:/run/secrets/vault:ro

  backend-vault-test:
    build:
      target: dev
    volumes: !override
      - ./backend:/app
      - backend_node_modules:/app/node_modules
      - vault_auth_runtime_secret:/run/secrets/auth:ro
      - vault_backend_runtime_secret:/run/secrets/backend:ro
      - vault_migration_secret:/run/secrets/migration:ro

  auth:
    build:
      target: dev
    volumes: !override
      - ./auth:/app
      - vault_auth_runtime_secret:/run/secrets/vault:ro
