services:
  rustfs:
    environment:
      RUSTFS_CONSOLE_ENABLE: "false"

  nginx:
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -fksS --connect-timeout 2 --resolve tomato.iops.dev:8443:127.0.0.1 https://tomato.iops.dev:8443/ > /dev/null",
        ]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 10s
    environment:
      MODSEC_RULE_ENGINE: "On"
      MODSEC_AUDIT_LOG: /dev/stdout
      MODSEC_AUDIT_LOG_FORMAT: JSON
      MODSEC_AUDIT_LOG_PARTS: FH
      RESOLVER_CONFIG: valid=15s ipv6=off
      FRONTEND_PORT: 80
