// Using Prisma-generated types as the single source of truth
// for database enums and models. This ensures consistency
// between the Prisma schema and TypeScript types.
import { ProjectStatus } from "@prisma/client";

// dto != model
// include only the things client is allowed to send when creating a project
// ex: we dont include id because it is generated by the database (uuid). its
// not something that should be set by the client.
// TODO: Decide on validation strategy for DTOs:
// - Option 1: class-validator + ValidationPipe (NestJS standard)
// Example:
//  import { IsString, IsOptional, IsEnum, IsBoolean } from "class-validator";
//  @IsString()
//  name: string;
// - Option 2: Zod schema-based validation
// For now, DTO is kept unvalidated during scaffolding phase.
export class CreateProjectDto {
  name: string;
  description?: string;
  deadline?: string;
  status?: ProjectStatus; // defaults to IN_PROGRESS in Prisma
  isArchived?: boolean;
}
