// Using Prisma-generated types as the single source of truth
// for database enums and models. This ensures consistency
// between the Prisma schema and TypeScript types.
import { ProjectStatus } from "@prisma/client";
import {
  IsBoolean,
  IsDateString,
  IsEnum,
  IsOptional,
  IsString,
} from "class-validator";

// dto != model
// include only the things client is allowed to send when creating a project
// ex: we dont include id because it is generated by the database (uuid). its
// not something that should be set by the client.
export class CreateProjectDto {
  @IsString()
  name: string;

  @IsOptional()
  @IsString()
  description?: string;

  @IsOptional()
  @IsDateString()
  deadline?: string;

  @IsOptional()
  @IsEnum(ProjectStatus)
  status?: ProjectStatus; // defaults to IN_PROGRESS in Prisma

  @IsOptional()
  @IsBoolean()
  isArchived?: boolean;
}
