/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicTermsRouteImport } from './routes/_public/terms'
import { Route as PublicPrivacyRouteImport } from './routes/_public/privacy'
import { Route as PublicForgotPasswordRouteImport } from './routes/_public/forgot-password'
import { Route as PublicContactRouteImport } from './routes/_public/contact'
import { Route as PublicAboutRouteImport } from './routes/_public/about'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedProjectIdRouteRouteImport } from './routes/_authenticated/$projectId/route'
import { Route as AuthenticatedProjectIdSummaryRouteImport } from './routes/_authenticated/$projectId/summary'
import { Route as AuthenticatedProjectIdListRouteImport } from './routes/_authenticated/$projectId/list'
import { Route as AuthenticatedProjectIdKanbanRouteImport } from './routes/_authenticated/$projectId/kanban'
import { Route as AuthenticatedProjectIdEvaluationChecklistRouteImport } from './routes/_authenticated/$projectId/evaluation-checklist'
import { Route as AuthenticatedProjectIdDiscoveryRouteImport } from './routes/_authenticated/$projectId/discovery'
import { Route as AuthenticatedProjectIdCalendarRouteImport } from './routes/_authenticated/$projectId/calendar'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicTermsRoute = PublicTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicPrivacyRoute = PublicPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicForgotPasswordRoute = PublicForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectIdRouteRoute =
  AuthenticatedProjectIdRouteRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectIdSummaryRoute =
  AuthenticatedProjectIdSummaryRouteImport.update({
    id: '/summary',
    path: '/summary',
    getParentRoute: () => AuthenticatedProjectIdRouteRoute,
  } as any)
const AuthenticatedProjectIdListRoute =
  AuthenticatedProjectIdListRouteImport.update({
    id: '/list',
    path: '/list',
    getParentRoute: () => AuthenticatedProjectIdRouteRoute,
  } as any)
const AuthenticatedProjectIdKanbanRoute =
  AuthenticatedProjectIdKanbanRouteImport.update({
    id: '/kanban',
    path: '/kanban',
    getParentRoute: () => AuthenticatedProjectIdRouteRoute,
  } as any)
const AuthenticatedProjectIdEvaluationChecklistRoute =
  AuthenticatedProjectIdEvaluationChecklistRouteImport.update({
    id: '/evaluation-checklist',
    path: '/evaluation-checklist',
    getParentRoute: () => AuthenticatedProjectIdRouteRoute,
  } as any)
const AuthenticatedProjectIdDiscoveryRoute =
  AuthenticatedProjectIdDiscoveryRouteImport.update({
    id: '/discovery',
    path: '/discovery',
    getParentRoute: () => AuthenticatedProjectIdRouteRoute,
  } as any)
const AuthenticatedProjectIdCalendarRoute =
  AuthenticatedProjectIdCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedProjectIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/$projectId': typeof AuthenticatedProjectIdRouteRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/about': typeof PublicAboutRoute
  '/contact': typeof PublicContactRoute
  '/forgot-password': typeof PublicForgotPasswordRoute
  '/privacy': typeof PublicPrivacyRoute
  '/terms': typeof PublicTermsRoute
  '/$projectId/calendar': typeof AuthenticatedProjectIdCalendarRoute
  '/$projectId/discovery': typeof AuthenticatedProjectIdDiscoveryRoute
  '/$projectId/evaluation-checklist': typeof AuthenticatedProjectIdEvaluationChecklistRoute
  '/$projectId/kanban': typeof AuthenticatedProjectIdKanbanRoute
  '/$projectId/list': typeof AuthenticatedProjectIdListRoute
  '/$projectId/summary': typeof AuthenticatedProjectIdSummaryRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/$projectId': typeof AuthenticatedProjectIdRouteRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/about': typeof PublicAboutRoute
  '/contact': typeof PublicContactRoute
  '/forgot-password': typeof PublicForgotPasswordRoute
  '/privacy': typeof PublicPrivacyRoute
  '/terms': typeof PublicTermsRoute
  '/$projectId/calendar': typeof AuthenticatedProjectIdCalendarRoute
  '/$projectId/discovery': typeof AuthenticatedProjectIdDiscoveryRoute
  '/$projectId/evaluation-checklist': typeof AuthenticatedProjectIdEvaluationChecklistRoute
  '/$projectId/kanban': typeof AuthenticatedProjectIdKanbanRoute
  '/$projectId/list': typeof AuthenticatedProjectIdListRoute
  '/$projectId/summary': typeof AuthenticatedProjectIdSummaryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_authenticated/$projectId': typeof AuthenticatedProjectIdRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_public/about': typeof PublicAboutRoute
  '/_public/contact': typeof PublicContactRoute
  '/_public/forgot-password': typeof PublicForgotPasswordRoute
  '/_public/privacy': typeof PublicPrivacyRoute
  '/_public/terms': typeof PublicTermsRoute
  '/_public/': typeof PublicIndexRoute
  '/_authenticated/$projectId/calendar': typeof AuthenticatedProjectIdCalendarRoute
  '/_authenticated/$projectId/discovery': typeof AuthenticatedProjectIdDiscoveryRoute
  '/_authenticated/$projectId/evaluation-checklist': typeof AuthenticatedProjectIdEvaluationChecklistRoute
  '/_authenticated/$projectId/kanban': typeof AuthenticatedProjectIdKanbanRoute
  '/_authenticated/$projectId/list': typeof AuthenticatedProjectIdListRoute
  '/_authenticated/$projectId/summary': typeof AuthenticatedProjectIdSummaryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$projectId'
    | '/dashboard'
    | '/about'
    | '/contact'
    | '/forgot-password'
    | '/privacy'
    | '/terms'
    | '/$projectId/calendar'
    | '/$projectId/discovery'
    | '/$projectId/evaluation-checklist'
    | '/$projectId/kanban'
    | '/$projectId/list'
    | '/$projectId/summary'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$projectId'
    | '/dashboard'
    | '/about'
    | '/contact'
    | '/forgot-password'
    | '/privacy'
    | '/terms'
    | '/$projectId/calendar'
    | '/$projectId/discovery'
    | '/$projectId/evaluation-checklist'
    | '/$projectId/kanban'
    | '/$projectId/list'
    | '/$projectId/summary'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_public'
    | '/_authenticated/$projectId'
    | '/_authenticated/dashboard'
    | '/_public/about'
    | '/_public/contact'
    | '/_public/forgot-password'
    | '/_public/privacy'
    | '/_public/terms'
    | '/_public/'
    | '/_authenticated/$projectId/calendar'
    | '/_authenticated/$projectId/discovery'
    | '/_authenticated/$projectId/evaluation-checklist'
    | '/_authenticated/$projectId/kanban'
    | '/_authenticated/$projectId/list'
    | '/_authenticated/$projectId/summary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/terms': {
      id: '/_public/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof PublicTermsRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/privacy': {
      id: '/_public/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PublicPrivacyRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/forgot-password': {
      id: '/_public/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof PublicForgotPasswordRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/$projectId': {
      id: '/_authenticated/$projectId'
      path: '/$projectId'
      fullPath: '/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectIdRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/$projectId/summary': {
      id: '/_authenticated/$projectId/summary'
      path: '/summary'
      fullPath: '/$projectId/summary'
      preLoaderRoute: typeof AuthenticatedProjectIdSummaryRouteImport
      parentRoute: typeof AuthenticatedProjectIdRouteRoute
    }
    '/_authenticated/$projectId/list': {
      id: '/_authenticated/$projectId/list'
      path: '/list'
      fullPath: '/$projectId/list'
      preLoaderRoute: typeof AuthenticatedProjectIdListRouteImport
      parentRoute: typeof AuthenticatedProjectIdRouteRoute
    }
    '/_authenticated/$projectId/kanban': {
      id: '/_authenticated/$projectId/kanban'
      path: '/kanban'
      fullPath: '/$projectId/kanban'
      preLoaderRoute: typeof AuthenticatedProjectIdKanbanRouteImport
      parentRoute: typeof AuthenticatedProjectIdRouteRoute
    }
    '/_authenticated/$projectId/evaluation-checklist': {
      id: '/_authenticated/$projectId/evaluation-checklist'
      path: '/evaluation-checklist'
      fullPath: '/$projectId/evaluation-checklist'
      preLoaderRoute: typeof AuthenticatedProjectIdEvaluationChecklistRouteImport
      parentRoute: typeof AuthenticatedProjectIdRouteRoute
    }
    '/_authenticated/$projectId/discovery': {
      id: '/_authenticated/$projectId/discovery'
      path: '/discovery'
      fullPath: '/$projectId/discovery'
      preLoaderRoute: typeof AuthenticatedProjectIdDiscoveryRouteImport
      parentRoute: typeof AuthenticatedProjectIdRouteRoute
    }
    '/_authenticated/$projectId/calendar': {
      id: '/_authenticated/$projectId/calendar'
      path: '/calendar'
      fullPath: '/$projectId/calendar'
      preLoaderRoute: typeof AuthenticatedProjectIdCalendarRouteImport
      parentRoute: typeof AuthenticatedProjectIdRouteRoute
    }
  }
}

interface AuthenticatedProjectIdRouteRouteChildren {
  AuthenticatedProjectIdCalendarRoute: typeof AuthenticatedProjectIdCalendarRoute
  AuthenticatedProjectIdDiscoveryRoute: typeof AuthenticatedProjectIdDiscoveryRoute
  AuthenticatedProjectIdEvaluationChecklistRoute: typeof AuthenticatedProjectIdEvaluationChecklistRoute
  AuthenticatedProjectIdKanbanRoute: typeof AuthenticatedProjectIdKanbanRoute
  AuthenticatedProjectIdListRoute: typeof AuthenticatedProjectIdListRoute
  AuthenticatedProjectIdSummaryRoute: typeof AuthenticatedProjectIdSummaryRoute
}

const AuthenticatedProjectIdRouteRouteChildren: AuthenticatedProjectIdRouteRouteChildren =
  {
    AuthenticatedProjectIdCalendarRoute: AuthenticatedProjectIdCalendarRoute,
    AuthenticatedProjectIdDiscoveryRoute: AuthenticatedProjectIdDiscoveryRoute,
    AuthenticatedProjectIdEvaluationChecklistRoute:
      AuthenticatedProjectIdEvaluationChecklistRoute,
    AuthenticatedProjectIdKanbanRoute: AuthenticatedProjectIdKanbanRoute,
    AuthenticatedProjectIdListRoute: AuthenticatedProjectIdListRoute,
    AuthenticatedProjectIdSummaryRoute: AuthenticatedProjectIdSummaryRoute,
  }

const AuthenticatedProjectIdRouteRouteWithChildren =
  AuthenticatedProjectIdRouteRoute._addFileChildren(
    AuthenticatedProjectIdRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedProjectIdRouteRoute: typeof AuthenticatedProjectIdRouteRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedProjectIdRouteRoute:
    AuthenticatedProjectIdRouteRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PublicRouteRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicContactRoute: typeof PublicContactRoute
  PublicForgotPasswordRoute: typeof PublicForgotPasswordRoute
  PublicPrivacyRoute: typeof PublicPrivacyRoute
  PublicTermsRoute: typeof PublicTermsRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicContactRoute: PublicContactRoute,
  PublicForgotPasswordRoute: PublicForgotPasswordRoute,
  PublicPrivacyRoute: PublicPrivacyRoute,
  PublicTermsRoute: PublicTermsRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
